<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FinanceOS.Budget.Application\FinanceOS.Budget.Application.csproj" />
    <ProjectReference Include="..\FinanceOS.Budget.Domain\FinanceOS.Budget.Domain.csproj" />
    <ProjectReference Include="..\..\..\contracts\FinanceOS.Contracts\FinanceOS.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
