apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financeos
  namespace: financeos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "2000"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - financeos.51-210-40-78.sslip.io
      secretName: financeos-tls
  rules:
    - host: financeos.51-210-40-78.sslip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: financeos-gateway
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financeos-web
  namespace: financeos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "1000"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - financeos.51-210-40-78.sslip.io
      secretName: financeos-tls
  rules:
    - host: financeos.51-210-40-78.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: financeos-web
                port:
                  number: 80
