<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\FinanceOS.BuildingBlocks\FinanceOS.BuildingBlocks.csproj" />
    <ProjectReference Include="..\FinanceOS.Identity.Application\FinanceOS.Identity.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
