apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - auth-config.yaml
  - gateway.yaml
  - identity-api.yaml
  - finance-api.yaml
  - budget-api.yaml
  - notification-api.yaml
  - web-auth-config.yaml
  - web.yaml
